export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const SET_INIT_POSITION = 'SET_INIT_POSITION';
export const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES';
export const MOVE_NODE = 'MOVE_NODE';
